
# apps.yaml is looking at ./apps/staging directory for application definitions
# In the .apps/staging directory there will be a kustomization.yaml file defining the apps to be deployed in staging cluster

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  # dependsOn:
  # - name: infro-configs
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age

